[windows]
plugin_folder = "$HOME/Documents/Derivative/Plugins"

[macos]
plugin_folder = "$HOME/Library/Application Support/Derivative/TouchDesigner099/Plugins"
python_include_dir = "/Applications/TouchDesigner.app/Contents/MacOS/TouchEngine.app/Contents/Frameworks/Python.framework/Headers"